### PR TITLE
5.3.3

### PR DESCRIPTION
**Pull request by TheHmmka**
Fix an issue with random delays.

### CODE REVIEW

**Comment by sbertix** [comment]
Hey @TheHmmka, thanks for the PR. 
I'm struggling to see how it's any different than `5.3.2`, though 🤔 

---

Edit:
I'm assuming the misunderstanding comes from `main` (the original base branch for your PR) targeting `v7.0.0`, which has basically nothing in common with `v5.*` (getting the occasional update just because of **Swiftagram** still relying on it).

**Review by sbertix — COMMENTED** [review]
Aren't you just remaining the variable? 🤔

**Comment by TheHmmka** [comment]
> Aren't you just remaining the variable? 🤔

Well, randomization didn’t work and all request used the same delay for each page. But nowadays we are so lazy to dig in to someone code (your architecture is not an ice cream in a hot day ☺️) So I just put your class to ChatGPT and it suggested to change the name of the switch case from “delay” to other cause it “override” the value.

Sorry it’s in Russian but you can translate:
 https://chatgpt.com/share/67116ef0-b850-8008-b430-879aa013682d

Well I just tried and now it works. That’s why I created pull request.

Cheers! 🤙🏻

**Comment by sbertix** [comment]
> your architecture is not an ice cream in a hot day ☺️

I can't blame you 😅 I've tried commenting most of it but there's a lot of abstractions to try and follow. It's not easy. 

> Well, randomization didn’t work and all request used the same delay for each page. 

OK, now I understand what's *really* changing in your code. Indeed the following `Pager`, at line 105, uses the unwrapped `delay`, instead of the `struct` one, so renaming it does in fact change things.
I missed it too at first glance. Apologies. Thank you, merging this.

**Comment by TheHmmka** [comment]
> I can't blame you 😅 I've tried commenting most of it but there's a lot of abstractions to try and follow. It's not easy.

Yeah, I feel the beauty in your flow but my subordinate developers can't fly at those speeds. ☺️

Thanks for accepting the request. Now I can delete my fork! 🤙🏻

**Pull request merged**
